name: pullcounter
version: 0.0.1+1
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  core_resources:
    git:
      path: core_resources
      url: https://github.com/icarohs7/unox-flutter-resmodules
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^6.2.0
  hive_flutter: ^1.1.0
  stream_resources:
    git:
      path: stream_resources
      url: https://github.com/icarohs7/unox-flutter-resmodules
  triple_fp_resources:
    git:
      path: triple_fp_resources
      url: https://github.com/icarohs7/unox-flutter-resmodules
  value_notifier_resources:
    git:
      path: value_notifier_resources
      url: https://github.com/icarohs7/unox-flutter-resmodules
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true